version : '3.8'
services:
  mysql:
    image: mysql:8.0
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_DATABASE: quartz
    ports:
      - "3306:3306"
